// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using portal_urbano.Data;

#nullable disable

namespace portal_urbano.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522001000_AddReporteUnicoPorUsuario")]
    partial class AddReporteUnicoPorUsuario
    {
    }
}
